---
name: Super-Linter

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    lint:
        uses: thewildmage/dotfiles/.github/workflows/linter.yaml@v1
        secrets:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
