---
name: Super-Linter

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        uses: thewildmage/dotfiles/.github/workflows/linter.yaml@v1
        secrets:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
